[package]
name = "snarkvm-console-types-string"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Type operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-network]
path = "../../network"
version = "0.7.5"

[dependencies.snarkvm-console-types-field]
path = "../field"
version = "0.7.5"

[dependencies.snarkvm-console-types-integers]
path = "../integers"
version = "0.7.5"
