[package]
name = "snarkvm-console-types-address"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Type operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-network-environment]
path = "../../network/environment"
version = "0.7.5"

[dependencies.snarkvm-console-types-field]
path = "../field"
version = "0.7.5"

[dependencies.snarkvm-console-types-group]
path = "../group"
version = "0.7.5"

[dev-dependencies.snarkvm-console-account]
path = "../../account"
version = "0.7.5"
default-features = false
features = ["private_key"]
