[package]
name = "snarkvm"
version = "0.9.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "Decentralized private computations"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[[bin]]
name = "snarkvm"
path = "snarkVM/main.rs"

[workspace]
members = ["errors", "models", "utilities"]

[dependencies]

[dev-dependencies]
rusty-hook = { version = "0.10.3" }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0
debug-assertions = true
debug = true
