[package]
name = "snarkvm"
version = "0.0.1"
authors = ["howardwu <howardwu@berkeley.edu>"]
edition = "2018"

[workspace]
members = ["algorithms", "curves", "dpc", "errors", "gadgets", "models", "objects", "parameters", "polycommit", "storage", "testing", "utilities"]

[dependencies]
