[package]
name = "snarkvm-console-account"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Account operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-network]
path = "../network"
version = "0.7.5"

[dependencies.snarkvm-console-types]
path = "../types"
version = "0.7.5"

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"

[dependencies.base58]
version = "0.2"

[dependencies.serde]
version = "1.0"

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.serde_json]
version = "1.0"
