[package]
name = "snarkvm-posw"
version = "0.0.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Proof of Succinct Work circuit implementation based on [KB20]"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-errors]
path = "../errors"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-gadgets]
path = "../gadgets"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-marlin]
path = "../marlin"
version = "0.0.5"

[dependencies.snarkvm-models]
path = "../models"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-polycommit]
path = "../polycommit"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-objects]
path = "../objects"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-parameters]
path = "../parameters"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.0.5"
default-features = false

[dependencies.blake2]
version = "0.9"
default-features = false

[dependencies.rand]
version = "0.8"

[dependencies.thiserror]
version = "1.0.24"

[dev-dependencies.rand_xorshift]
version = "0.3.0"
default-features = false

[features]
print-trace = [ "snarkvm-profiler/print-trace" ]
test-helpers = [ ]
