[package]
name = "snarkvm-testing"
version = "0.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Testing suite for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { path = "../algorithms", version = "0.0.0"}
snarkvm-curves = { path = "../curves", version = "0.0.0"}
snarkvm-dpc = { path = "../dpc", version = "0.0.0"}
snarkvm-errors = { path = "../errors", version = "0.0.0"}
snarkvm-models = { path = "../models", version = "0.0.0"}
snarkvm-objects = { path = "../objects", version = "0.0.0"}
snarkvm-parameters = { path = "../parameters", version = "0.0.0"}
snarkvm-storage = { path = "../storage", version = "0.0.0"}
snarkvm-utilities = { path = "../utilities", version = "0.0.0"}

once_cell = { version = "1.5.2" }
rand = { version = "0.7.0" }
rand_xorshift = { version = "0.2.0" }
tokio = { version = "0.2.22", features = ["full"] }
