[package]
name = "snarkvm-wasm"
version = "0.0.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "WASM for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = [ "cdylib", "rlib" ]

#[dependencies.snarkvm-algorithms]
#path = "../algorithms"
#version = "0.0.5"
#default-features = false

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-errors]
path = "../errors"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-models]
path = "../models"
version = "0.0.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.0.5"

[dependencies.derivative]
version = "2"

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.rand_xorshift]
version = "0.3"
default-features = false

[dependencies.serde]
version = "1.0.123"
default-features = false
features = [ "derive" ]

[dependencies.wasm-bindgen]
version = "0.2"
features = [ "serde-serialize" ]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.20"
