[package]
name = "snarkvm-sponge"
version = "0.6.0"
authors = ["arkworks contributors", "The Aleo Team <hello@aleo.org>" ]
description = "An implementation of the cryptographic sponge functions for zkSNARK from arkworks-rs/sponge"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.6.0"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.6.0"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.6.0"

[features]
default = [ ]
