[package]
name = "snarkvm-snarkos-integration"
version = "0.2.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A test suite for functionalities requiring snarkOS integration"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-curves]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-dpc]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-fields]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-gadgets]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-objects]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-parameters]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-profiler]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-r1cs]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-utilities]
version = "0.2.2"
default-features = false

[dependencies.anyhow]
version = "1.0.38"

[dependencies.base58]
version = "0.1"

[dependencies.bech32]
version = "0.6"

[dependencies.blake2]
version = "0.9"

[dependencies.derivative]
version = "2"

[dependencies.hex]
version = "0.4.3"

[dependencies.itertools]
version = "0.10.0"

[dependencies.rand]
version = "0.8"

[dependencies.snarkos-storage]
git = "https://github.com/ljedrz/snarkOS"
rev = "2eca11a85989bab2f5ea00854f7efdfab7859d95"
default-features = false
features = ["mem_storage"]

[dependencies.snarkos-testing]
git = "https://github.com/ljedrz/snarkOS"
rev = "2eca11a85989bab2f5ea00854f7efdfab7859d95"
default-features = false

[dependencies.thiserror]
version = "1.0"

[dependencies.rand_xorshift]
version = "0.3"
