[package]
name = "snarkvm-storage"
version = "0.0.1"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Storage for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { path = "../algorithms", version = "0.0.1"}
snarkvm-errors = { path = "../errors", version = "0.0.1"}
snarkvm-models = { path = "../models", version = "0.0.1"}
snarkvm-objects = { path = "../objects", version = "0.0.1"}
snarkvm-parameters = { path = "../parameters", version = "0.0.1"}
snarkvm-utilities = { path = "../utilities", version = "0.0.1"}

bincode = { version = "1.3.1" }
hex = { version = "0.4.2" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7" }
rocksdb = { version = "0.15.0" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
snarkvm-curves = { path = "../curves" }
snarkvm-testing = { path = "../testing" }
