[package]
name = "snarkvm-circuits-core"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Core circuits library for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-circuits-core-aleo]
path = "./aleo"
version = "0.7.5"

[dependencies.snarkvm-circuits-core-algorithms]
path = "./algorithms"
version = "0.7.5"
