[package]
name = "snarkvm-circuits-core"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Core circuits library for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.7.5"
default-features = false
features = ["crypto_hash"]

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"

[dependencies.snarkvm-circuits-types]
path = "../types"
version = "0.7.5"

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"

[dependencies.enum_index]
version = "0.2"

[dependencies.enum_index_derive]
version = "0.2"

[dependencies.nom]
version = "7.1"

[dependencies.once_cell]
version = "*"

[dev-dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.7.5"
default-features = false
features = ["prf", "signature"]
