[package]
name = "snarkvm-algorithms"
version = "0.0.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Algorithms for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[[bench]]
name = "snark"
path = "benches/snark/snark.rs"
harness = false

[[example]]
name = "gm17"
path = "examples/snark/gm17.rs"

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.0.6"
default-features = false

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.0.6"
default-features = false

[dependencies.snarkvm-profiler]
path = "../profiler"
version = "0.0.6"
default-features = false

[dependencies.snarkvm-r1cs]
path = "../r1cs"
version = "0.0.6"
default-features = false

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.0.6"
default-features = false

[dependencies.blake2]
version = "0.9"

[dependencies.derivative]
version = "2"

[dependencies.digest]
version = "0.9"

[dependencies.itertools]
version = "0.10.0"

[dependencies.rand]
version = "0.8"

[dependencies.rand_chacha]
version = "0.3"

[dependencies.rayon]
version = "1"

[dependencies.sha2]
version = "0.9"

[dependencies.smallvec]
version = "1.6"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.criterion]
version = "0.3.4"

[dev-dependencies.csv]
version = "1"

[dev-dependencies.rand_xorshift]
version = "0.3"

[features]
default = [
  "pedersen-parallel",
  "snarkvm-r1cs/default",
  "snarkvm-utilities/default"
]
pedersen-parallel = [ ]
print-trace = [ "snarkvm-profiler/print-trace" ]
