[package]
name = "snarkvm-console"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Console environment for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-console-account]
path = "./account"
version = "0.7.5"
optional = true

[dependencies.snarkvm-console-algorithms]
path = "./algorithms"
version = "0.7.5"
optional = true

[dependencies.snarkvm-console-network]
path = "./network"
version = "0.7.5"
optional = true

[dependencies.snarkvm-console-program]
path = "./program"
version = "0.7.5"
optional = true

[dependencies.snarkvm-console-types]
path = "./types"
version = "0.7.5"
optional = true

[features]
default = [ "account", "algorithms", "network", "program", "types" ]
account = [ "network", "snarkvm-console-account" ]
algorithms = [ "snarkvm-console-algorithms" ]
network = [ "snarkvm-console-network" ]
program = [ "network", "snarkvm-console-program" ]
types = [ "snarkvm-console-types" ]
