[package]
name = "snarkvm-console"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Native console operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"
