[package]
name = "snarkvm-circuit-algorithms"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Algorithm circuit library for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-circuit-environment]
path = "../environment"
version = "0.7.5"

[dependencies.snarkvm-circuit-types]
path = "../types"
version = "0.7.5"

[dependencies.snarkvm-console-algorithms]
path = "../../console/algorithms"
version = "0.7.5"

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"

[dev-dependencies.snarkvm-algorithms]
path = "../../algorithms"
version = "0.7.5"
default-features = false
features = ["crh", "merkle_tree"]

[dev-dependencies.anyhow]
version = "1.0.57"
